name: CI Front

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-front:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # adapte si tu utilises une autre version

      - name: Installer les dépendances
        run: npm ci

      - name: Compiler le projet
        run: npm run build

      - name: Lancer les tests (si définis)
        run: npm run test || echo "Pas de tests définis"
