name: CI Front

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # adapte si tu utilises une autre version

      - name: Installer les dépendances
        run: npm ci

      - name: Compiler le projet
        run: npm run build

      - name: Lancer les tests (si définis)
        run: npm run test || echo "Pas de tests définis"
  deploy:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Build du projet Vite
        run: npm install && npm run build

      - name: Build de l’image Docker avec Nginx
        run: docker build -t cesizen-front .

      - name: Supprimer l'ancien conteneur s’il existe
        run: docker rm -f cesizen-front || true

      - name: Lancer le conteneur Docker avec nom fixe
        run: docker run -d --name cesizen-front -p 8080:80 cesizen-front
